Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "k3s-worker-1"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "k3s-worker-1"
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.network "private_network", ip: "192.168.56.11"

  config.vm.provision "shell", inline: <<-SCRIPT
    echo "Worker node 1 ready for provisioning"
  SCRIPT
end
