Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "k3s-master"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "k3s-master"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision "shell", inline: <<-SCRIPT
    echo "Master node ready for provisioning"
  SCRIPT
end
